### ISSUE TITLE
rtt_rosnode: loadROSService() overrides one from rtt_ros

### ISSUE THREAD

**Issue by mjbogusz** [orocos/rtt_ros_integration#110]
The global function `loadROSService()` in `rtt_rosnode/src/ros_plugin.cpp` added in 6ae4950eae59daf3332cf498be2e38e249365570 apparently overrides one with the same name residing in `rtt_ros/src/rtt_ros_service.cpp` (probably during linking).

This causes the 'import' operation to never be registered thus breaking anything using that operation. Simple renaming the function within the file solved the issue (at least in my usecase) - it's not referenced anywhere outside the file.

---

As an additional note (though I'm not sure about this one), shouldn't it register as providing `"rosnode"` instead of `"ros"`, to be consistent with the name reported in `getRTTPluginName()`?

**Comment by meyerj** [comment]
Thanks for reporting! #111 should fix the issue.

> As an additional note (though I'm not sure about this one), shouldn't it register as providing "rosnode" instead of "ros", to be consistent with the name reported in getRTTPluginName()?

It used to be a deliberate choice to collect all operations provided by one of the services in this repo in the `ros` global service (or at least the most common ones), independent of the package name (https://github.com/orocos/rtt_ros_integration/pull/21). RTT does not enforce that the name of the plugin matches the package or service name.

**Comment by disRecord** [comment]
Thanks for the report and the fix! 
Before I proposed this change I had not tried to load `rtt_ronode` and `rtt_ros` together. My bad...
