### ISSUE TITLE
Diagnose unit test failures

### ISSUE THREAD

**Issue by jbohren** [orocos/rtt_ros_integration#12]
From: https://github.com/orocos/rtt_ros_integration/pull/10#issuecomment-31672167

@meyerj 

> Do you have an idea why the tests are failing in Travis for orocos/rtt_ros_integration.git?
> https://travis-ci.org/orocos/rtt_ros_integration/builds/16476426
> For some reason Travis still reports a successful build despite of the failed tests.

The tests weren't failing a month ago, and nothing in rtt_ros changed, so I think it might be something that changed in rtt, itself: https://travis-ci.org/jhu-lcsr-forks/rtt_ros_integration/builds/15534262

It also looks like even then, there are some false errors reported even thought things are properly loaded.

I don't know why catkin_make run_tests is returning 0, though.

**Comment by meyerj** [comment]
Travis is installing the orocos_toolchain packages from the ROS Ubuntu repository now, but the latest version that has the env-hook to set the `RTT_COMPONENT_PATH` is not public yet. I think it is a matter of time until the newest version of ros-hydro-rtt is in http://packages.ros.org/ros/ubuntu/ and after that the tests should be successful.

**Comment by jbohren** [comment]
So we can reduce the synchronization problems by using the ROS shadow-fixed repositories in tests. I added this to the ros_ci_bootstrap script. Results here: https://travis-ci.org/jhu-lcsr-forks/rtt_ros_integration/builds/16547206

I cleaned up some of the false errors in ros.import in this PR: https://github.com/orocos/rtt_ros_integration/pull/14

Also, it looks like the `catkin_test_results` script will output an error code if any tests failed: https://github.com/ros/catkin/issues/392

I've added this in https://github.com/jhu-lcsr-forks/rtt_ros_integration/commit/1b127493df5bb31ff26b3b640c30c22a81d3d2db
