### ISSUE TITLE
plan for ROS 2.0?

### ISSUE THREAD

**Issue by jacknlliu** [orocos/rtt_ros_integration#143]
Is this project intended to be further compatible with ROS 2.0?

**Comment by meyerj** [comment]
Yes, we are planning to upgrade rtt_ros_integration to ROS 2 in the near future.

**Comment by jacknlliu** [comment]
I think Orocos is still a very powerful supplement for the ROS 2.0, especially in some cases where the DDS does not include the shared memory mechanism.
