### ISSUE TITLE
rtt_create_pkg vs rtt_create_msgs

### ISSUE THREAD

**Issue by smits** [orocos/rtt_ros_integration#22]
The documentation still uses rtt_create_msgs while the tool itself was renamed to rtt_create_pkg. @jbohren  What was the reasoning for the name switch? Could we revert it back to *_msgs?

**Comment by jbohren** [comment]
This changed because you can also independently generate ROS service proxies. I won't mind if we get rid of the combined command and just require the two macros to be called explicitly.

**Comment by meyerj** [comment]
Ruben's comment was not about the cmake macros, but about the [script](https://github.com/orocos/rtt_ros_integration/blob/5772397166c6e52a6a1cb7f892991f1e78eeede8/rtt_roscomm/scripts/create_rtt_pkg) to create typekit/service proxy messages. (The cmake macros are currently named `ros_generate_rtt_typekit()` and `ros_generate_rtt_service_proxies()`).

I personally would keep the suffix `_msgs`, as a service definition is just a special type of message in a wider sense. That would mean to rename the script back to `create_rtt_msgs`. The current name `create_rtt_pkg` does not express the relation to typekits at all and could be mixed up with `orocreate-pkg`.

**Comment by jbohren** [comment]
Yeah, I'm fine with that change, as well.
