### ISSUE TITLE
Building Orocos From Source for target Xenomai

### ISSUE THREAD

**Issue by cfpperche2** [orocos/rtt_ros_integration#38]
How to ?

Using Ubuntu 12.04, Xenomai 2.6.4 properly installed

**Comment by meyerj** [comment]
This question is already quite old, but did you try to compile [rtt](https://github.com/orocos-toolchain/rtt), [ocl](https://github.com/orocos-toolchain/ocl) and rtt_ros_integration with the `OROCOS_TARGET` environment (or cmake) variable set to `xenomai` [1]? There have been some negative reports in the past [2]. The pre-built binaries for the Orocos Toolchain and rtt_ros_integration released in ROS are only for the gnulinux target, but if you cannot compile the packages from source for other targets this would be a bug.

[1] http://www.orocos.org/stable/documentation/rtt/v2.x/doc-xml/orocos-installation.html#basic-install-unix
[2] http://www.orocos.org/forum/orocos/orocos-users/rttrosnode-files-compile-orocostargetxenomai
