### ISSUE TITLE
rtt_rosparam: translate float value less than 0.0001 from ros parameter to orocos property  fail

### ISSUE THREAD

**Issue by joe271828** [orocos/rtt_ros_integration#82]
The warning log like this: 
0.542 [ Warning][ROSParamService::getParam] Could not convert "speed" from an XMLRPC value to an RTT property.

**Comment by ahoarau** [comment]
What functions are you using ?

**Comment by joe271828** [comment]
I'm using the getParam function.

**Comment by meyerj** [comment]
I cannot reproduce the issue. Which version of RTT and rtt_rosparam are you using?

Are you sure that the parameter speed has type double? The ROS parameter server also stores the [type of each parameter](http://wiki.ros.org/Parameter%20Server#Parameter_Types), one of string, double, int or bool. Unfortunately the `rosparam` command line tool is not explicit about the type. If you set it as `rosparam set /param 1e-10` the resulting type is string, not double and rtt_rosparam would output the quoted error message.  Try `rosparam set /param 1.e-10` or `rosparam set /param 0.0000000001` instead.

Maybe the error message of rtt_rosparam should be more explicit and state the expected and found parameter type.

**Comment by joe271828** [comment]
@meyerj  Yes, you are right. Using `rosparam set /param 1.e-10` is OK. Thanks very much!
